[package]
name = "actix_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
async-trait = "0.1.80"
diesel = "2.2.0"
dotenv = "0.15.0"
serde = { version = "1.0.203", features = ["derive"] }
